import { ProductCategory } from "@/types";

export interface CategoryMetadata {
  category: ProductCategory;
  label: string;
  description: string;
  mandatoryFields: string[];
  optionalFields: string[];
  exemptFields: string[]; // Marked NOT_APPLICABLE
  standardQuantityUnits: string[];
}

export const CATEGORY_METADATA_MAP: Record<ProductCategory, CategoryMetadata> = {
  FOOTWEAR: {
    category: "FOOTWEAR",
    label: "Footwear (Shoes, Sandals, Slippers)",
    description: "Footwear packaged commodities under Legal Metrology & BIS footwear standards",
    mandatoryFields: [
      "productName",
      "genericName",
      "brandName",
      "articleCode",
      "style",
      "colour",
      "dimensionOrSize",
      "netQuantity",
      "netQuantityUnit",
      "mrp",
      "mrpInclusiveTaxes",
      "manufacturingDate",
      "countryOfOrigin",
      "manufacturerName",
      "manufacturerAddress",
      "consumerCarePhone",
      "consumerCareEmail",
    ],
    optionalFields: ["unitSalePrice", "productDescription", "batchNumber"],
    exemptFields: ["fssaiNumber", "ingredients", "expiryDate", "bestBefore"],
    standardQuantityUnits: ["Pair", "Pairs", "Piece", "Pieces", "Unit", "Units", "Set", "Sets", "N", "U"],
  },
  APPAREL: {
    category: "APPAREL",
    label: "Apparel & Garments",
    description: "Readymade garments, apparel, and textiles",
    mandatoryFields: [
      "productName",
      "genericName",
      "brandName",
      "style",
      "colour",
      "dimensionOrSize",
      "netQuantity",
      "netQuantityUnit",
      "mrp",
      "mrpInclusiveTaxes",
      "manufacturingDate",
      "countryOfOrigin",
      "manufacturerName",
      "manufacturerAddress",
      "consumerCarePhone",
      "consumerCareEmail",
    ],
    optionalFields: ["unitSalePrice", "productDescription", "articleCode"],
    exemptFields: ["fssaiNumber", "expiryDate", "bestBefore"],
    standardQuantityUnits: ["Piece", "Pieces", "Unit", "Units", "N", "U", "Set", "Sets"],
  },
  FOOD_BEVERAGE: {
    category: "FOOD_BEVERAGE",
    label: "Food & Beverages",
    description: "Packaged food, beverages, and consumable agricultural commodities",
    mandatoryFields: [
      "productName",
      "genericName",
      "netQuantity",
      "netQuantityUnit",
      "netQuantityValue",
      "mrp",
      "mrpInclusiveTaxes",
      "unitSalePrice",
      "manufacturingDate",
      "expiryDate",
      "fssaiNumber",
      "ingredients",
      "countryOfOrigin",
      "manufacturerName",
      "manufacturerAddress",
      "consumerCarePhone",
      "consumerCareEmail",
    ],
    optionalFields: ["productDescription", "batchNumber", "bestBefore"],
    exemptFields: ["footLength", "dimensionOrSize", "colour", "style", "articleCode"],
    standardQuantityUnits: ["g", "kg", "ml", "l", "L", "gm", "N", "U"],
  },
  COSMETICS_PERSONAL_CARE: {
    category: "COSMETICS_PERSONAL_CARE",
    label: "Cosmetics & Personal Care",
    description: "Body wash, shampoo, skin lotions, perfumes, and cosmetic formulations",
    mandatoryFields: [
      "productName",
      "genericName",
      "netQuantity",
      "netQuantityUnit",
      "netQuantityValue",
      "mrp",
      "mrpInclusiveTaxes",
      "unitSalePrice",
      "manufacturingDate",
      "expiryDate",
      "fssaiNumber", // State Mfg License
      "ingredients",
      "countryOfOrigin",
      "manufacturerName",
      "manufacturerAddress",
      "consumerCarePhone",
      "consumerCareEmail",
    ],
    optionalFields: ["productDescription", "batchNumber"],
    exemptFields: ["footLength", "dimensionOrSize", "style", "colour", "articleCode"],
    standardQuantityUnits: ["ml", "l", "L", "g", "kg", "gm", "fl oz"],
  },
  ELECTRONICS: {
    category: "ELECTRONICS",
    label: "Electronics & Electrical Appliances",
    description: "Consumer electronics, home appliances, chargers, and accessories",
    mandatoryFields: [
      "productName",
      "genericName",
      "brandName",
      "netQuantity",
      "netQuantityUnit",
      "mrp",
      "mrpInclusiveTaxes",
      "manufacturingDate",
      "countryOfOrigin",
      "manufacturerName",
      "manufacturerAddress",
      "consumerCarePhone",
      "consumerCareEmail",
    ],
    optionalFields: ["articleCode", "style", "unitSalePrice", "productDescription"],
    exemptFields: ["fssaiNumber", "ingredients", "expiryDate", "bestBefore"],
    standardQuantityUnits: ["Piece", "Pieces", "Unit", "Units", "Set", "Sets", "N", "U"],
  },
  GENERAL_COMMODITY: {
    category: "GENERAL_COMMODITY",
    label: "General Packaged Commodity",
    description: "General retail packaged goods",
    mandatoryFields: [
      "productName",
      "genericName",
      "netQuantity",
      "netQuantityUnit",
      "mrp",
      "mrpInclusiveTaxes",
      "manufacturingDate",
      "countryOfOrigin",
      "manufacturerName",
      "manufacturerAddress",
      "consumerCarePhone",
      "consumerCareEmail",
    ],
    optionalFields: ["unitSalePrice", "productDescription", "batchNumber"],
    exemptFields: [],
    standardQuantityUnits: ["g", "kg", "ml", "l", "L", "N", "U", "Piece", "Pair", "Set"],
  },
};
